name: osrm_pcd_uel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  accessibility_tools: ^2.2.1
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_tts: ^4.0.2
  geolocator: ^12.0.0
  get_it: ^7.7.0
  http: ^1.2.2
  signals: ^5.3.0
  vibration: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/success_sound.mp3
  uses-material-design: true
